### ISSUE TITLE
Wrong position of cursor

### ISSUE THREAD

**Issue by sulabhb** [SubhrajyotiSen/PasswordView#1]
Hello Subhrajyoti  i guess PasswordView class has one bug. When i type 1st letter cursor shifts one step left

**Comment by SubhrajyotiSen** [comment]
Hey!! Thanks for reporting. I was able to reproduce the issue and will fix it ASAP

**Comment by MiChongGET** [comment]
That give me a good example,Thank you!

**Comment by SubhrajyotiSen** [comment]
@sulabhbartaula please check the updated version. The cursor should be fixed
