### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by CelticParser** [SubhrajyotiSen/PasswordView#3]
HI, thnx for the widget and very useful for good a UX.

I discovered if the user uses the widget to shows the password and presses the backspace soft-key, the app force closes and an 

> IndexOutOfBoundsException: setSpan (7 ... 7) ends beyond length 6...

 is thrown at `com.subhrajyoti.passwordview;`, class `PasswordView` line 116 - `setSelection(this.cursorPosition);`

This does not happen when the password widget is not utilized by the user.

**Comment by SubhrajyotiSen** [comment]
Hey! Thanks for reporting the issue. I will look into it ASAP

**Comment by SubhrajyotiSen** [comment]
@CelticParser Hey! I would really suggest you use Design Support Library. It runs without any issues

**Comment by CelticParser** [comment]
Thnx. I was going to say the same thing - I was unaware that this function it had been added.
