### ISSUE TITLE
delete text

### ISSUE THREAD

**Issue by bambangfery** [SubhrajyotiSen/PasswordView#4]
oh man i just found your project and i think it's really for me
but i got problem i cannot delete text when password is visible. when i delete text app force close..
please help me man..
thanks man..

**Comment by SubhrajyotiSen** [comment]
Hey! Thanks for pointing it out but this library has been deprecated. The Google Design Library provides a passwordView implementation now. I would suggest you use that 😄

**Comment by bambangfery** [comment]
if you have a reference link to passwordview

**Comment by SubhrajyotiSen** [comment]
[https://medium.com/@moyinoluwa/password-visibility-toggle-android-support-library-revision-24-2-0-98b422087e5a](https://medium.com/@moyinoluwa/password-visibility-toggle-android-support-library-revision-24-2-0-98b422087e5a)

**Comment by bambangfery** [comment]
thanks man..
