### ISSUE TITLE
I found a Bug

### ISSUE THREAD

**Issue by zhoujia456888** [SubhrajyotiSen/PasswordView#5]
I found a Bug
Step 1: enter the password
Step 2: click on the icon to display the password
Step 3: click on the keyboard to delete
The program will flash back.

E/AndroidRuntime: FATAL EXCEPTION: main  Process: vip.samfriend.samfriendsmarthomewifi, PID: 30767
java.lang.IndexOutOfBoundsException: setSpan (10 ... 10) ends beyond length 9

**Comment by zhangweiquan** [comment]
I got same issue.

**Comment by victorlopesjg** [comment]
I got same issue.

**Comment by victorlopesjg** [comment]
I made the correction and requested the pull request, now just wait.

**Comment by SubhrajyotiSen** [comment]
v1.1.2 has been released with the fix thanks to @Victorlopesjg
